// get all musicians
GET http://localhost:5000/api/v1/musicians

###

// get single musician
GET http://localhost:5000/api/v1/musicians/6215401d9853e0c413e459cf

###

// add a musician
POST http://localhost:5000/api/v1/musicians
Content-Type: application/xml
Authorization: token xxx

<request>
    <name>sample</name>
    <time>Wed, 21 Oct 2015 18:27:50 GMT</time>
</request>

###

// edit a musician
PATCH http://localhost:5000/api/v1/musicians/""


###

// delete a musician
DELETE http://localhost:5000/api/v1/musicians/""
###